#!/usr/bin/env node
// ===========================================================================
// One-off vendoring script for the landing-page globe and the no-JS US map.
//
// FluTrack has zero dependencies, so the geo libraries and geometry are
// VENDORED (committed) rather than installed. This script regenerates every
// vendored file from pinned npm packages installed in a scratch directory:
//
//   mkdir /tmp/geo && cd /tmp/geo && npm init -y
//   npm install d3-geo@3.1.1 topojson-client@3.1.0 topojson-simplify@3.0.3 \
//               esbuild@0.24.2 world-atlas@2.0.2 us-atlas@3.0.1
//   node /path/to/FluTrack/scripts/vendor-geo.mjs --modules /tmp/geo/node_modules
//
// Outputs (all committed):
//   src/scripts/geo-vendor.js         d3-geo + topojson-client, only the
//                                     functions the globe uses (tree-shaken)
//   src/assets/geo/land-110m.json     Natural Earth land, simplified (ISC / PD)
//   src/assets/geo/us-states.json     US states, simplified, ids = state FIPS
//   src/scripts/us-svg-paths.js       Albers-USA SVG path per state, for the
//                                     no-JS fallback map (server-rendered)
//   src/server/county-names.js       county FIPS -> county name
//
// The globe budget (<= 45 KB gzipped for JS + geometry) is enforced by
// build/check.mjs, so a regenerated file that grows past it fails the build.
// ===========================================================================

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const argIdx = process.argv.indexOf('--modules');
if (argIdx === -1) {
  console.error('usage: node scripts/vendor-geo.mjs --modules <node_modules dir>');
  process.exit(2);
}
const mods = resolve(process.argv[argIdx + 1]);
const load = (p) => import(pathToFileURL(join(mods, p)).href);
const json = (p) => JSON.parse(readFileSync(join(mods, p), 'utf8'));

const simplify = await load('topojson-simplify/src/index.js');
const client = await load('topojson-client/src/index.js');
const d3 = await load('d3-geo/src/index.js');

/**
 * Simplify a topology, keeping `keep` (0..1) of its points, then drop the small
 * detached islands that simplification leaves as specks and re-quantize — the
 * same pipeline as `toposimplify -S <keep> -f`.
 */
function simplified(topology, keep, system = 'spherical') {
  const { transform } = topology;
  const pre = simplify.presimplify(topology, simplify[`${system}TriangleArea`]);
  const minWeight = simplify.quantile(pre, keep);
  let out = simplify.simplify(pre, minWeight);
  out = simplify.filter(out, simplify.filterAttachedWeight(out, minWeight, simplify[`${system}RingArea`]));
  return transform ? client.quantize(out, transform) : out;
}

/** Drop properties, keep ids, keep only the named objects. */
function strip(topology, keepObjects) {
  const objects = {};
  for (const name of keepObjects) {
    const obj = topology.objects[name];
    objects[name] = {
      ...obj,
      geometries: obj.geometries.map(({ type, arcs, id }) => (id != null ? { type, arcs, id } : { type, arcs })),
    };
  }
  return { ...topology, objects };
}

const write = (rel, text) => {
  const out = join(root, rel);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, text);
  console.log(`  wrote ${rel} (${text.length} bytes)`);
};

// --- Geometry for the globe ------------------------------------------------ //
const land = strip(simplified(json('world-atlas/land-110m.json'), 0.3), ['land']);
write('src/assets/geo/land-110m.json', JSON.stringify(land));

const statesTopo = strip(simplified(json('us-atlas/states-10m.json'), 0.05), ['states']);
write('src/assets/geo/us-states.json', JSON.stringify(statesTopo));

// --- No-JS fallback: pre-projected Albers USA paths, one per state -------- //
const albers = simplified(json('us-atlas/states-albers-10m.json'), 0.05, 'planar');
const albersStates = client.feature(albers, albers.objects.states).features;
const path = d3.geoPath().digits(0);
const paths = {};
for (const f of albersStates) {
  const d = path(f);
  if (d) paths[String(f.id).padStart(2, '0')] = d;
}
const [[x0, y0], [x1, y1]] = path.bounds(client.feature(albers, albers.objects.nation));
write(
  'src/scripts/us-svg-paths.js',
  `// Generated by scripts/vendor-geo.mjs from us-atlas@3.0.1 (states-albers-10m,\n` +
    `// simplified). Albers USA, pre-projected; keyed by 2-digit state FIPS.\n` +
    `// Used by the server-rendered (no-JS) result card. Do not edit by hand.\n` +
    `export const US_VIEWBOX = '${Math.floor(x0)} ${Math.floor(y0)} ${Math.ceil(x1 - x0)} ${Math.ceil(y1 - y0)}';\n` +
    `export const STATE_PATHS = ${JSON.stringify(paths)};\n`
);

// --- County names --------------------------------------------------------- //
const counties = json('us-atlas/counties-10m.json');
const names = {};
for (const g of counties.objects.counties.geometries) {
  if (g.id && g.properties?.name) names[String(g.id).padStart(5, '0')] = g.properties.name;
}
write(
  'src/server/county-names.js',
  `// Generated by scripts/vendor-geo.mjs from us-atlas@3.0.1 counties-10m\n` +
    `// (U.S. Census Bureau cartographic boundaries). County FIPS -> name.\n` +
    `// Do not edit by hand.\n` +
    `export const COUNTY_NAMES = ${JSON.stringify(names)};\n`
);

// --- d3-geo + topojson-client, tree-shaken -------------------------------- //
const entry = join(mods, '..', 'flutrack-geo-entry.js');
writeFileSync(
  entry,
  `export { geoOrthographic, geoPath, geoGraticule10, geoCentroid, geoInterpolate } from 'd3-geo';\n` +
    `export { feature, mesh } from 'topojson-client';\n`
);
const bundled = execFileSync(join(mods, '.bin', 'esbuild'), [entry, '--bundle', '--format=esm', '--minify', '--log-level=warning'], {
  cwd: join(mods, '..'),
}).toString();
write(
  'src/scripts/geo-vendor.js',
  `/*! Vendored by scripts/vendor-geo.mjs. d3-geo 3.1.1 (ISC, Mike Bostock), d3-array (ISC),\n` +
    ` topojson-client 3.1.0 (ISC, Mike Bostock). Only the exports listed in that script. */\n` +
    bundled
);
